---
apiVersion: v1
kind: Service
metadata:
  name: demo-remote-gradle-cache-svc
spec:
  selector:
    app.name: demo-remote-gradle-cache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5071
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-remote-gradle-cache-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: demo-remote-gradle-cache-svc
            port:
              number: 80
